### ISSUE TITLE
GLIBC 2.X not found on RHEL 5 - portable solution

### ISSUE THREAD

**Issue by richard-ostrochovsky** [skaji/relocatable-perl#10]
Hello,

I have this issue with using relocatable-perl on old RHEL 5:

../perl/bin/perl --version
../perl/bin/perl: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by ../perl/bin/perl)
../perl/bin/perl: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ../perl/bin/perl)
../perl/bin/perl: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by ../perl/bin/perl)
../perl/bin/perl: /lib64/libc.so.6: version `GLIBC_2.9' not found (required by ../perl/bin/perl)

Do you see some "portable solution" of this problem, without messing with old RHEL 5 libraries upgrading (I don't even have the permissions).

Thanks for your attention. I am looking forward to your reply.

Richard

**Comment by skaji** [comment]
rhel5 is not supported.

**Comment by skaji** [comment]
If you need relocatable perl for rhel5, please build it by yourself.

BTW, if you just want the latest perl, why don't you build it by yourself?
The build steps are relatively simple:
```
wget https://www.cpan.org/src/5.0/perl-5.30.1.tar.gz
tar xf perl-5.30.1.tar.gz
cd perl-5.30.1
./Configure -des -Dprefix=$HOME/perl
make -j8 install
$HOME/perl/bin/perl -V
```

**Comment by richard-ostrochovsky** [comment]
I just don't figured out this possibility, never did this before, but
everything is first time once. Thank your for nutritious tip.

Dňa pi 15. 11. 2019, 23:19 Shoichi Kaji <notifications@github.com>
napísal(a):
