### ISSUE TITLE
i686 binaries?

### ISSUE THREAD

**Issue by wdlkmpx** [skaji/relocatable-perl#15]
Would it be possible to create i686 binaries and add them to the releases?

I think the tar.xz files are enough, no need to create extra .tar.gz files for releases

**Comment by skaji** [comment]
I don't use i686 instances,
so I don't have a plan to support the architecture in this project.

You could build i686 binaries by yourself.

**Comment by wdlkmpx** [comment]
It's just x86_64 without the 64

I'll see if I can compile it. 

I can assure you nobody uses the Darwin build, but you compile it anyway as a service to others

**Comment by skaji** [comment]
I'm using darwin builds.

**Comment by wdlkmpx** [comment]
Ah ok, sorry then, I was being dramatic

The docker stuff seems a bit hard to adapt for i386, but I guess it can be done with the system perl and using something like `i386/debian` or `i386/alpine`, but I don't have a kernel that supports docker so I guess I'll just convert the docker stuff to a shell script and try to start building the relocatable perl in an alpine chroot
