### ISSUE TITLE
not 100% portable

### ISSUE THREAD

**Issue by mgood7123** [skaji/relocatable-perl#6]
could you please compile the binaries as statically linked instead of dynamically linked in order to produce a 100% portable perl

**Comment by mgood7123** [comment]
note they should be usable in a chroot:
sudo chroot ./relocatable-perl/ /perl/bin/perl

**Comment by mgood7123** [comment]
(note that compiling statically doesnt hinder any funtionality as perl from Static Get is compiled statically and it produces no errors in my scripts (however it was not compiled with threaded support so Thread::Pool cannot be used with it sadly)

**Comment by skaji** [comment]
According to INSTALL file in perl source code, if we compile perl statically, we won't be able to use any new extension (XS) module without recompiling perl itself.

So I won't compile perl statically for this repository.
But, of course, you can compile perl statically by yourself.
